---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "wkid.fullname" . }}
  labels:
    {{- include "wkid.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "wkid.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "wkid.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "wkid.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: {{ .Chart.Name }}-permissions
          image: "ubuntu:latest"
          command:
            - "chmod"
          args:
            - "g+r"
            - "/mnt/sa.pub"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml .root | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        - name: {{ .Chart.Name }}-jwks
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command:
            - "azwi"
          args:
            - "jwks"
            - "--public-keys"
            - "/mnt/sa.pub"
            - "--output-file"
            - "/out/jwks"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml .nonRoot | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: shared-data
              mountPath: /out
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
        - name: {{ .Chart.Name }}-issuer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command:
            - "yq"
          args:
            - |
              .spec.containers[0].command |= ( .
                  | del( .[] | select(. == "--service-account-issuer=*" ) )
                  | . += [
                      "--service-account-issuer={{ include "wkid.hostname" . }}",
                      "--service-account-issuer={{ .Values.apiServer.defaultIssuer }}"
                  ]
              )
            - -i
            - /mnt/kube-apiserver.yaml
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml .root | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: kube-apiserver
              mountPath: /mnt/kube-apiserver.yaml
              readOnly: false
            - name: tmp-data
              mountPath: /tmp
      containers:
        - name: nginx
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml .nonRoot | nindent 12 }}
          {{- end }}
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: {{ include "wkid.configMap" . }}
              mountPath: /usr/share/nginx/html/.well-known
            - name: shared-data
              mountPath: /usr/share/nginx/html/openid/v1
            - name: tmp-data
              mountPath: /tmp
      volumes:
        - name: kube-apiserver
          hostPath:
            path: {{ .Values.apiServer.path }}
            type: File
        - name: {{ include "wkid.configMap" . }}
          configMap:
            name: {{ include "wkid.configMap" . }}
            optional: false
        - name: shared-data
          emptyDir: {}
        - name: tmp-data
          emptyDir: {}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
